// Package main is the entry point for the REST API service.
// It wires up the chi router, connects to Postgres via the shared internal/db
// package, and serves HTTP with graceful shutdown on SIGINT/SIGTERM.
//
// Swagger docs are generated by running:
//
//	swag init -g cmd/api/main.go -o cmd/api/docs
//
// The Swagger UI is available at http://localhost:8080/swagger/index.html when
// the server is started with SWAGGER_ENABLED=true. It is disabled by default to
// avoid exposing API schema details in production (OWASP A05).
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"mcp-server/internal/db"
	"mcp-server/internal/handler"

	_ "mcp-server/cmd/api/docs"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/httprate"
	httpSwagger "github.com/swaggo/http-swagger"
)

//	@title			MCP Server REST API
//	@version		1.0
//	@description	REST interface for the MCP server tools (calculator, dad jokes) and operational endpoints. Intended for use with JMeter load testing.
//	@contact.name	MCP Server
//	@license.name	MIT

//	@host		localhost:8080
//	@BasePath	/

//	@schemes	http

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	// Warn operators when running with insecure defaults so misconfigurations
	// surface immediately in logs rather than silently in production.
	if os.Getenv("DATABASE_URL") == "" {
		logger.Warn("DATABASE_URL is not set; database connection will fail")
	}

	connectCtx, connectCancel := context.WithTimeout(context.Background(), 10*time.Second)
	pool, err := db.Connect(connectCtx, os.Getenv("DATABASE_URL"))
	connectCancel()
	if err != nil {
		logger.Error("failed to connect to database", "error", err)
		os.Exit(1)
	}

	r := chi.NewRouter()

	// RequestID and RealIP must come first so that all subsequent middleware
	// and handlers see the correct request ID and client IP.
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)

	// OWASP A05: set defensive HTTP response headers on every response.
	r.Use(handler.SecurityHeaders)

	// OWASP A09: emit a structured log line for every request, including
	// status code (for 4xx/5xx detection) and request ID for correlation.
	r.Use(handler.RequestLogger(logger))

	// OWASP A01: per-IP rate limiting — 60 requests per minute across all
	// endpoints. Adjust via RATE_LIMIT_RPM if higher throughput is needed
	// for JMeter runs (set to 0 to disable).
	rpm := 60
	r.Use(httprate.LimitByIP(rpm, time.Minute))

	r.Use(middleware.Recoverer)

	// Operational endpoints.
	r.Get("/health", handler.Health(pool, logger))

	// Tool endpoints — these mirror the MCP tools exposed over stdio,
	// but as plain HTTP so JMeter (or any HTTP client) can exercise them.
	r.Route("/tools", func(r chi.Router) {
		r.Post("/calculate", handler.Calculate(logger))
		r.Get("/dad-joke", handler.DadJoke(logger))
	})

	// OWASP A05: Swagger UI is disabled by default to avoid advertising API
	// structure in production environments. Set SWAGGER_ENABLED=true to enable.
	// The underlying spec JSON lives at /swagger/doc.json.
	if envOr("SWAGGER_ENABLED", "false") == "true" {
		r.Get("/swagger/*", httpSwagger.Handler(
			httpSwagger.URL("/swagger/doc.json"),
		))
		logger.Info("swagger UI enabled", "url", "http://localhost:"+envOr("PORT", "8080")+"/swagger/index.html")
	}

	addr := ":" + envOr("PORT", "8080")
	srv := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("api listening", "addr", addr)
		if err := srv.ListenAndServe(); !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-quit:
		logger.Info("shutting down", "signal", sig)
	case err := <-serverErr:
		logger.Error("server error", "error", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		logger.Error("graceful shutdown failed", "error", err)
	}

	pool.Close()
	logger.Info("shutdown complete")
}

// envOr returns the value of the environment variable key, or fallback if unset or empty.
func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
