// Package main is the entry point for the REST API service.
// It wires up the chi router, connects to Postgres via the shared internal/db
// package, and serves HTTP with graceful shutdown on SIGINT/SIGTERM.
//
// Swagger docs are generated by running:
//
//	swag init -g cmd/api/main.go -o cmd/api/docs
//
// The Swagger UI is available at http://localhost:8080/swagger/index.html
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"mcp-server/internal/db"
	"mcp-server/internal/handler"

	_ "mcp-server/cmd/api/docs"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
)

//	@title			MCP Server REST API
//	@version		1.0
//	@description	REST interface for the MCP server tools (calculator, dad jokes) and operational endpoints. Intended for use with JMeter load testing.
//	@contact.name	MCP Server
//	@license.name	MIT

//	@host		localhost:8080
//	@BasePath	/

//	@schemes	http

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	connectCtx, connectCancel := context.WithTimeout(context.Background(), 10*time.Second)
	pool, err := db.Connect(connectCtx, os.Getenv("DATABASE_URL"))
	connectCancel()
	if err != nil {
		logger.Error("failed to connect to database", "error", err)
		os.Exit(1)
	}

	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Recoverer)

	// Operational endpoints.
	r.Get("/health", handler.Health(pool, logger))

	// Tool endpoints — these mirror the MCP tools exposed over stdio,
	// but as plain HTTP so JMeter (or any HTTP client) can exercise them.
	r.Route("/tools", func(r chi.Router) {
		r.Post("/calculate", handler.Calculate(logger))
		r.Get("/dad-joke", handler.DadJoke(logger))
	})

	// Swagger UI — served at /swagger/index.html.
	// The underlying spec JSON is at /swagger/doc.json.
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	addr := ":" + envOr("PORT", "8080")
	srv := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("api listening", "addr", addr, "swagger", "http://localhost"+addr+"/swagger/index.html")
		if err := srv.ListenAndServe(); !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-quit:
		logger.Info("shutting down", "signal", sig)
	case err := <-serverErr:
		logger.Error("server error", "error", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		logger.Error("graceful shutdown failed", "error", err)
	}

	pool.Close()
	logger.Info("shutdown complete")
}

// envOr returns the value of the environment variable key, or fallback if unset or empty.
func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
