// Package main is the entry point for the REST API service.
// It wires up the chi router, connects to Postgres via the shared internal/db
// package, and serves HTTP with graceful shutdown on SIGINT/SIGTERM.
//
// Swagger docs are generated by running:
//
//	swag init -g cmd/api/main.go -o cmd/api/docs
//
// The Swagger UI is available at http://localhost:8080/swagger/index.html when
// the server is started with SWAGGER_ENABLED=true. It is disabled by default to
// avoid exposing API schema details in production (OWASP A05).
package main

import (
	"context"
	"errors"
	"log/slog"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"mcp-server/internal/db"
	"mcp-server/internal/handler"

	_ "mcp-server/cmd/api/docs"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/httprate"
	httpSwagger "github.com/swaggo/http-swagger"
)

//	@title			MCP Server REST API
//	@version		1.0
//	@description	REST interface for the MCP server tools (calculator, dad jokes) and operational endpoints. Intended for use with JMeter load testing.
//	@contact.name	MCP Server
//	@license.name	MIT

//	@host		localhost:8080
//	@BasePath	/

//	@schemes	http

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	// Build the database DSN from environment variables, warning if no
	// credentials are configured so misconfigurations surface early.
	dsn := dsnFromEnv()
	if dsn == "" {
		logger.Warn("no database credentials set; database connection will fail")
	}

	connectCtx, connectCancel := context.WithTimeout(context.Background(), 10*time.Second)
	pool, err := db.Connect(connectCtx, dsn)
	connectCancel()
	if err != nil {
		logger.Error("failed to connect to database", "error", err)
		os.Exit(1)
	}

	r := chi.NewRouter()

	// RequestID must be first so every subsequent middleware and handler has a
	// request ID available for correlation.
	r.Use(middleware.RequestID)

	// OWASP A01: per-IP rate limiting applied before RealIP so the limiter
	// always uses the true TCP-level RemoteAddr and cannot be bypassed by
	// rotating X-Forwarded-For / X-Real-IP headers.
	//
	// Read RATE_LIMIT_RPM from the environment (default 60). Set to 0 to
	// disable rate limiting entirely (useful for JMeter load tests).
	rpm, rpmErr := strconv.Atoi(envOr("RATE_LIMIT_RPM", "60"))
	if rpmErr != nil || rpm < 0 {
		logger.Warn("invalid RATE_LIMIT_RPM value; defaulting to 60", "value", envOr("RATE_LIMIT_RPM", "60"))
		rpm = 60
	}
	if rpm > 0 {
		r.Use(httprate.LimitByIP(rpm, time.Minute))
	}

	// RealIP rewrites RemoteAddr from forwarding headers. It runs after the
	// rate limiter so the limiter is not affected by client-controlled headers.
	r.Use(middleware.RealIP)

	// OWASP A05: set defensive HTTP response headers on every response.
	r.Use(handler.SecurityHeaders)

	// OWASP A09: emit a structured log line for every request, including
	// status code (for 4xx/5xx detection) and request ID for correlation.
	r.Use(handler.RequestLogger(logger))

	r.Use(middleware.Recoverer)

	// Operational endpoints.
	r.Get("/health", handler.Health(pool, logger))

	// Tool endpoints — these mirror the MCP tools exposed over stdio,
	// but as plain HTTP so JMeter (or any HTTP client) can exercise them.
	r.Route("/tools", func(r chi.Router) {
		r.Post("/calculate", handler.Calculate(logger))
		r.Get("/dad-joke", handler.DadJoke(logger))
	})

	// OWASP A05: Swagger UI is disabled by default to avoid advertising API
	// structure in production environments. Set SWAGGER_ENABLED=true to enable.
	// The underlying spec JSON lives at /swagger/doc.json.
	if envOr("SWAGGER_ENABLED", "false") == "true" {
		r.Get("/swagger/*", httpSwagger.Handler(
			httpSwagger.URL("/swagger/doc.json"),
		))
		logger.Info("swagger UI enabled", "url", "http://localhost:"+envOr("PORT", "8080")+"/swagger/index.html")
	}

	addr := ":" + envOr("PORT", "8080")
	srv := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("api listening", "addr", addr)
		if err := srv.ListenAndServe(); !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-quit:
		logger.Info("shutting down", "signal", sig)
	case err := <-serverErr:
		logger.Error("server error", "error", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		logger.Error("graceful shutdown failed", "error", err)
	}

	pool.Close()
	logger.Info("shutdown complete")
}

// envOr returns the value of the environment variable key, or fallback if unset or empty.
func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// dsnFromEnv builds a Postgres DSN from environment variables.
//
// If DATABASE_URL is set it is returned as-is (for backward compatibility with
// direct binary runs where the caller has already composed the DSN).
// Otherwise, the DSN is assembled from the individual POSTGRES_* variables
// with proper URL encoding so that passwords containing characters reserved in
// URIs (e.g. "/" from openssl rand -base64 output) are handled correctly.
func dsnFromEnv() string {
	if dsn := os.Getenv("DATABASE_URL"); dsn != "" {
		return dsn
	}

	user := os.Getenv("POSTGRES_USER")
	password := os.Getenv("POSTGRES_PASSWORD")
	host := envOr("POSTGRES_HOST", "localhost")
	port := envOr("POSTGRES_PORT", "5432")
	dbName := os.Getenv("POSTGRES_DB")

	if user == "" || dbName == "" {
		// Caller (main) checks for empty DSN and logs a warning before
		// attempting to connect, so returning "" here is intentional.
		return ""
	}

	u := &url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(user, password),
		Host:   net.JoinHostPort(host, port),
		Path:   "/" + dbName,
	}
	return u.String()
}
